/* Generated By:JavaCC: Do not edit this line. TheBakingLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TheBakingLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INGREDIENT = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\".\"",
    "\",\"",
    "\"Mix\"",
    "\"combine\"",
    "\"with\"",
    "\"to\"",
    "\"make\"",
    "\"Bake\"",
    "\"cup\"",
    "\"tbl\"",
    "\"tsp\"",
    "\"for\"",
    "\"at\"",
    "\"Fahrenheit\"",
    "\"Celsius\"",
    "<INGREDIENT>",
    "<NUMBER>",
    "<LETTER>",
    "<IDENTIFIER>",
    "\"mins\"",
    "\"hours\"",
  };

}
