/* Generated By:JavaCC: Do not edit this line. TheBakingLangConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TheBakingLangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 35;
  /** RegularExpression Id. */
  int LETTER = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int INGREDIENT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\".\"",
    "\",\"",
    "\"Mix\"",
    "\"combine\"",
    "\"with\"",
    "\"to\"",
    "\"make\"",
    "\"Bake\"",
    "\"cup\"",
    "\"tbl\"",
    "\"tsp\"",
    "\"flour\"",
    "\"egg\"",
    "\"sugar\"",
    "\"honey\"",
    "\"cocoa\"",
    "\"vanilla\"",
    "\"cinnamon\"",
    "\"butter\"",
    "\"vegetable\"",
    "\"oil\"",
    "\"milk\"",
    "\"water\"",
    "\"baking\"",
    "\"soda\"",
    "\"powder\"",
    "\"for\"",
    "\"at\"",
    "\"Fahrenheit\"",
    "\"Celsius\"",
    "<NUMBER>",
    "<LETTER>",
    "<IDENTIFIER>",
    "<INGREDIENT>",
    "\"mins\"",
    "\"hours\"",
  };

}
